name: Almendros React CI

on:
  push:
    branches: [main, release, develop]
  pull_request:
    branches: [main, release, develop]

jobs:
  build:
    name: Lint and Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      # Paso importante: Configurar NPM para evitar módulos nativos
      - name: Configure NPM
        run: |
          echo "ROLLUP_SKIP_NODEJS_NATIVE=1" >> $GITHUB_ENV
          echo "VITE_BUILD_FORCE=1" >> $GITHUB_ENV
          npm config set node-linker hoisted

      - name: Install dependencies
        run: |
          npm ci
          # Instalamos versiones puras de JS de dependencias problemáticas
          npm install --no-save rollup

      - name: Lint code
        run: npm run lint
        continue-on-error: true

      - name: Build TypeScript
        run: npx tsc -b
        continue-on-error: true

      - name: Build project
        run: npx vite build --force
        env:
          # Variables de entorno para deshabilitar optimizaciones problemáticas
          NODE_ENV: production
          ROLLUP_SKIP_NODEJS_NATIVE: 1
          VITE_DISABLE_OPTIMIZATION: true

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: dist/
