name: Almendros React CI

on:
  push:
    branches: [main, release, develop]
  pull_request:
    branches: [main, release, develop]

jobs:
  build:
    name: Lint and Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x' # Usar Node.js 20.x para evitar problemas con Rollup
          cache: 'npm' # Habilitamos el cache ya que ahora tienes package-lock.json

      - name: Install dependencies
        run: npm ci # Volvemos a usar npm ci para una instalación más rápida y consistente

      - name: Lint code
        run: npm run lint
        continue-on-error: true

      - name: Build project
        run: npm run build
        env:
          ROLLUP_SKIP_NODEJS_NATIVE: true # Variable adicional para prevenir problemas con Rollup

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: dist/
